package guicafeteriautm;

import guicafeteriautm.utilerias.fondoPantalla;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author santi
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
       fondoPantalla fondo = new fondoPantalla();
    initComponents();
    // Maximiza la ventana al iniciar
    setExtendedState(JFrame. MAXIMIZED_BOTH);
    // Establece tamaño personalizado en función del ancho de la pantalla y una altura fija
    Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
    setSize(pantalla.width, 700);
    // Asigna imagen de fondo al panel principal (desktopPane)
    if (desktopPane != null) {
    desktopPane.setBorder(fondo); // Asegúrate de que fondo esté correctamente definido
    }
    // Establece el icono de la aplicación si la imagen existe
    try {
      ImageIcon iconoApp = new ImageIcon(getClass().getResource("/guicafeteriautm/imagenes/pato.png"));
        setIconImage(iconoApp.getImage());
    } catch (NullPointerException e) {
    System.err.println("No se pudo cargar el icono de la aplicación: " + e.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        opcUsuarios = new javax.swing.JMenuItem();
        opcUsuarios1 = new javax.swing.JMenuItem();
        opcEmpleados = new javax.swing.JMenuItem();
        opcAlimentos = new javax.swing.JMenuItem();
        opcBebidas = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenu();
        opcLevantar = new javax.swing.JMenuItem();
        opcCobrar = new javax.swing.JMenuItem();
        opcConsultar = new javax.swing.JMenuItem();
        mnuReporteVentas = new javax.swing.JMenu();
        opcVer = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        opcSalir = new javax.swing.JMenuItem();

        jMenu1.setText("Menu texto");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuUsuarios.setMnemonic('f');
        mnuUsuarios.setText("Gestion");

        opcUsuarios.setMnemonic('o');
        opcUsuarios.setText("Usuarios");
        opcUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(opcUsuarios);

        opcUsuarios1.setMnemonic('o');
        opcUsuarios1.setText("Clientes");
        opcUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcUsuarios1ActionPerformed(evt);
            }
        });
        mnuUsuarios.add(opcUsuarios1);

        opcEmpleados.setMnemonic('s');
        opcEmpleados.setText("Empleados");
        mnuUsuarios.add(opcEmpleados);

        opcAlimentos.setMnemonic('a');
        opcAlimentos.setText("Alimentos");
        mnuUsuarios.add(opcAlimentos);

        opcBebidas.setMnemonic('a');
        opcBebidas.setText("Bebidas");
        mnuUsuarios.add(opcBebidas);

        menuBar.add(mnuUsuarios);
        mnuUsuarios.getAccessibleContext().setAccessibleName("file");

        mnuPedidos.setMnemonic('e');
        mnuPedidos.setText("Pedidos");

        opcLevantar.setMnemonic('t');
        opcLevantar.setText("levantar¿");
        mnuPedidos.add(opcLevantar);

        opcCobrar.setMnemonic('y');
        opcCobrar.setText("Cobrar");
        mnuPedidos.add(opcCobrar);

        opcConsultar.setMnemonic('p');
        opcConsultar.setText("Consultar");
        mnuPedidos.add(opcConsultar);

        menuBar.add(mnuPedidos);

        mnuReporteVentas.setMnemonic('h');
        mnuReporteVentas.setText("Reportes");

        opcVer.setMnemonic('c');
        opcVer.setText("ver");
        mnuReporteVentas.add(opcVer);

        menuBar.add(mnuReporteVentas);

        mnuSalir.setText("Salir");

        opcSalir.setMnemonic('x');
        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(opcSalir);

        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcUsuariosActionPerformed
    frmGestionUsuarios ventanaGUI;
        try {
            ventanaGUI = new frmGestionUsuarios();   
            this.desktopPane.add(ventanaGUI);
            ventanaGUI.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_opcUsuariosActionPerformed

    private void opcUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcUsuarios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcUsuarios1ActionPerformed

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JMenu mnuReporteVentas;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JMenuItem opcAlimentos;
    private javax.swing.JMenuItem opcBebidas;
    private javax.swing.JMenuItem opcCobrar;
    private javax.swing.JMenuItem opcConsultar;
    private javax.swing.JMenuItem opcEmpleados;
    private javax.swing.JMenuItem opcLevantar;
    private javax.swing.JMenuItem opcSalir;
    private javax.swing.JMenuItem opcUsuarios;
    private javax.swing.JMenuItem opcUsuarios1;
    private javax.swing.JMenuItem opcVer;
    // End of variables declaration//GEN-END:variables

}
